version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      # Mount the images directory to the app container
      - ${STATIC_PATH}:${STATIC_PATH}